name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::539935451710:role/GitHubActionsRole
          role-session-name: GitHubActions
          aws-region: us-west-2

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

      - name: Build and tag Docker image
        run: |
          docker build -t my-app:latest .
          docker tag my-app:latest ${{ secrets.ECR_REPO }}/my-app:latest

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.ECR_REPO }}/my-app:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster paramesh-cluster --service app-service --force-new-deployment
